version: '3.8'

services:
  security:
    build: .
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - ENVIRONMENT=${ENVIRONMENT}
      - KAFKA_TOPICS=${KAFKA_TOPICS}
      - USER_COGNITO_POOL_ID=${USER_COGNITO_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
    env_file:
      - .env